version: '3.7'

services:
  magento:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.magento
    volumes:
      - ./magento2:/var/www/html
    container_name: magento_php
    ports:
      - "84:80"
      - "9000:9000"
    hostname: local.magento2.com
    links:
      - mariadbserver
      - elasticsearch
      - redis
    networks:
      - magento2-network
    depends_on:
      - mariadbserver
      - elasticsearch
      - redis

  mariadbserver:
    image: mariadb:10.6
    command: --innodb-use-native-aio=0
    ports:
      - "3307:3306"
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: magento
      MARIADB_ROOT_PASSWORD: root
    container_name: magento_mariadb
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - magento2-network

  elasticsearch:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    container_name: magento_elasticsearch
    networks:
      - elastic-net
      - magento2-network
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: magento_redis
    volumes:
      - redisdata:/data
    networks:
      - magento2-network

  nginx:
    image: nginx:latest
    container_name: magento_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./magento2:/var/www/html
    networks:
      - magento2-network
    depends_on:
      - magento
      
networks:
  elastic-net:
    driver: bridge
  magento2-network:
    driver: bridge

volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
  mariadbdata:
    driver: local