FROM php:8.3-fpm

# Install required PHP extensions and other dependencies
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    libicu-dev \
    libxml2-dev \
    libxslt1-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd zip intl pdo_mysql bcmath sockets soap xsl \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apt-get clean

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set PHP memory limit
RUN echo "memory_limit=2G" > /usr/local/etc/php/conf.d/memory-limit.ini

EXPOSE 9000

WORKDIR /var/www/html
